version: '3.7'

volumes:
  postgres_data: {}
  pgadmin: {}


x-extract:
  &extract
  build:
    context: extract
    args:
      - CHADWICK_VERSION
      - RETROSHEET_VERSION
      - BASEBALLDATABANK_VERSION
      - BUILD_ENV
  image: ${REPO}:extract-${VERSION}
x-ddl:
  &ddl
  build:
    context: transform
    dockerfile: ddl.Dockerfile
    args:
      - VERSION
  image: ${REPO}:ddl-${VERSION}  
x-parquet:
  &parquet
  build:
    context: transform
    dockerfile: parquet.Dockerfile
    args:
      - VERSION
  image: ${REPO}:parquet-${VERSION}
  depends_on:
    - extract
x-csv:
  &csv
  build:
    context: transform
    dockerfile: csv.Dockerfile
    args:
      - VERSION
  image: ${REPO}:csv-${VERSION}
  depends_on:
    - extract

x-clickhouse:
  &clickhouse
  build:
    context: load/clickhouse
    args:
      - VERSION
  image: ${REPO}:clickhouse-${VERSION}
  volumes:
    - ~/boxball/clickhouse:/var/lib/clickhouse
  depends_on:
    - parquet
    - ddl

x-drill:
  &drill
  container_name: drill
  # build:
  #   context: load/drill
  #   args:
  #     - VERSION
  image: drill/apache-drill  
  working_dir: /data
  command: [/bin/bash]
  ports:
    - 8047:8047
    - 31010:31010 
  volumes:    
    - ./load/drill/data:/data
  #depends_on:
  #  - parquet
  #  - ddl

x-postgres:
  &postgres
  build:
    context: load/postgres
    args:
      - VERSION
  image: ${REPO}:postgres-${VERSION}
  volumes:
    - ~/boxball/postgres:/var/lib/postgresql/data
  depends_on:
    - csv
    - ddl

x-postgres-cstore-fdw:
  &postgres-cstore-fdw
  build:
    context: load/postgres_cstore_fdw
    args:
      - VERSION
  image: ${REPO}:postgres-cstore-fdw-${VERSION}
  volumes:
    - ~/boxball/postgres-cstore-fdw:/var/lib/postgresql/data
  depends_on:
    - csv
    - ddl


x-pgadmin:
  &pgadmin
  container_name: pgadmin
  image: dpage/pgadmin4
  depends_on: [postgres-parquet-fdw]
  environment:
    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@test.com}
    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
  volumes:    
    - pgadmin:/var/lib/pgadmin
    - ./load/postgres_parquet_fdw/files:/data
  ports:
    - '7500:80'
  restart: unless-stopped
        
x-postgres-parquet-fdw:
  &postgres-parquet-fdw
  container_name: postgres_parquet_fdw
  environment: 
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  ports:
    - 5432:5432
  build:
    context: load/postgres_parquet_fdw
  volumes:
    - ./load/postgres_parquet_fdw/files:/data
    - ./load/postgres_parquet_fdw/db-files:/var/lib/postgresql/data      
    #  - postgres_data:/var/lib/postgresql/data

x-mysql:
  &mysql
  build:
    context: load/mysql
    args:
      - VERSION
  image: ${REPO}:mysql-${VERSION}
  volumes:
    - ~/boxball/mysql:/var/lib/mysql
  depends_on:
    - csv
    - ddl

x-sqlite:
  &sqlite
  build:
    context: load/sqlite
    args:
      - VERSION
  image: ${REPO}:sqlite-${VERSION}
  volumes:
    - ~/boxball/sqlite:/db
  depends_on:
    - csv
    - ddl


services:
  extract:
    << : *extract
  extract-latest:
    << : *extract
    image: ${REPO}:extract-latest

  ddl:
    << : *ddl
  ddl-latest:
    << : *ddl
    image: ${REPO}:ddl-latest

  parquet:
    << : *parquet
  parquet-latest:
    << : *parquet
    image: ${REPO}:parquet-latest

  csv:
    << : *csv
  csv-latest:
    << : *csv
    image: ${REPO}:csv-latest

  clickhouse:
    << : *clickhouse
  clickhouse-latest:
    << : *clickhouse
    image: ${REPO}:clickhouse-latest

  drill:
    << : *drill
  drill-latest:
    << : *drill
    image: ${REPO}:drill-latest

  postgres:
    << : *postgres
  postgres-latest:
    << : *postgres
    image: ${REPO}:postgres-latest

  postgres-cstore-fdw:
    << : *postgres-cstore-fdw
  postgres-cstore-fdw-latest:
    << : *postgres-cstore-fdw
    image: ${REPO}:postgres-cstore-fdw-latest

  postgres-parquet-fdw:
    << : *postgres-parquet-fdw
  
  pgadmin:
    << : *pgadmin

  mysql:
    << : *mysql
  mysql-latest:
    << : *mysql
    image: ${REPO}:mysql-latest

  sqlite:
    << : *sqlite
  sqlite-latest:
    << : *sqlite
    image: ${REPO}:sqlite-latest

